config/routes.rb
Rails.application.routes.draw do
  namespace :website, {
    path: '',
    constraints: {
      subdomain: ['', 'www', 'bajasmiledentistry']
    }
  } do

    root 'pages#home'

    controller :pages do
      get 'about-us'
      get 'contact-us'
      get 'price-list'
      get 'the-team'
      get 'virtual-tour'
    end

    resources :leads, only: [:new, :create, :edit], param: :uuid do
      collection do
        post :create_and_confirm_and_send_confirmation_emails
      end
      member do
        patch :update_and_confirm_and_send_confirmation_emails
        get :thanks
      end
    end
    resources :posts, only: [:index, :show]
    resources :treatments, only: [:index, :show]
  end
end

app/models/lead.rb
# TODO - Add status change timestamps
# TODO - Add status dependant validations
# TODO - Remove timezone from date validations
class Lead < OrganizationRecord
  has_many :item_lead_mappings, dependent: :destroy
  has_many :items, through: :item_lead_mappings

  enum preferred_time_range: {
    ANYTIME: 0,
    MORNING: 10,
    AFTERNOON: 20,
    EVENING: 30
  }
  enum preferred_conversation_channel: {
    PHONE: 0,
    EMAIL: 10
  }
  enum source: {
    WEBSITE: 0
  }
  enum status: {
    DRAFT: 0,
    SUBMITTED: 10,
    ACCEPTED: 20,
    REJECTED: 30,
    CANCELLED: 40
  }

  validates :email_address, {
    presence: true,
    email: true
  }
  validates :message, {
    length: {
      in: 0..2048
    },
    allow_nil: true
  }
  validates :person_name, {
    presence: true,
    length: {
      in: 1..255
    }
  }
  validates :phone_country_code, {
    presence: true
  }
  validates :phone_number, {
    presence: true,
    numericality: {
      only_integer: true
    },
    phone: {
      possible: true,
      types: [
        :personal_number,
        :fixed_or_mobile,
        :voip
      ],
      country_specifier: -> lead { lead.phone_country_code },
      extensions: false
    }
  }
  validates :preferred_date, {
    presence: true,
    date: {
      after: proc { 1.day.ago - 8.hours }
    },
    on: :create
  }
  validates :preferred_date, {
    presence: true,
    date: true,
    on: :update
  }
  validates :source, {
    presence: true
  }
  validates :status, {
    presence: true
  }
  validates :uuid, {
    uniqueness: {
      scope: %i[owning_organization_id]
    },
    presence: true,
  }

  before_validation(on: :create) do
    self.uuid ||= calculated_uuid
    self.status ||= 'DRAFT'
  end

  def calculated_uuid
    return unless self.owning_organization

    calculated_uuid = nil

    loop do
      calculated_uuid = SecureRandom.uuid

      break unless self.class.exists?(
        owning_organization: self.owning_organization,
        uuid: calculated_uuid
      )
    end

    calculated_uuid
  end

  def to_param
    self.uuid
  end
end

app/controllers/website/cities_controller.rb
module Website
  class CitiesController < WebsiteController
    def show
    end
  end
end

app/controllers/website/countries_controller.rb
module Website
  class CountriesController < WebsiteController
    def index
    end
    
    def show
    end
  end
end

app/controllers/website/leads_controller.rb
module Website
  class LeadsController < WebsiteController
    before_action :load_phones
    before_action :load_treatments
    before_action :load_items, only: [:new, :edit]

    def new
      @lead = Lead.new
    end

    def edit
      @lead ||= Lead.find_by!(owning_organization: current_organization, uuid: params[:uuid])
    end

    def create
      @lead = Lead.new(permitted_parameters)
      @lead.source = :WEBSITE
      @lead.save!
      redirect_to controller: :leads, action: :edit, uuid: @lead.uuid
    end

    # TODO: DRY
    def create_and_confirm_and_send_confirmation_emails
      @lead = Lead.new(permitted_parameters)
      @lead.source = :WEBSITE
      @lead.save!
      confirm
      send_confirmation_emails
      create_trello_card
      redirect_to controller: :leads, action: :thanks, uuid: @lead.uuid
    end

    def update_and_confirm_and_send_confirmation_emails
      update
      confirm
      send_confirmation_emails
      create_trello_card
      redirect_to controller: :leads, action: :thanks, uuid: @lead.uuid
    end

    def thanks
      @lead ||= Lead.find_by!(owning_organization: current_organization, uuid: params[:uuid])
    end

    private

    def create_trello_card
      return unless ENV.fetch("SUBMIT_LEADS_TO_TRELLO") == "1"
      @lead ||= Lead.find_by!(owning_organization: current_organization, uuid: params[:uuid])

      description = <<~DESCRIPTION
        Source: Website

        Name: #{@lead.person_name}
        Email: #{@lead.email_address}
        Telephone Number: #{@lead.phone_number}
        Preferred Conversation Channel: #{@lead.preferred_conversation_channel}
        Custom Message: #{@lead.message}
        Preferred Appointment Date: #{@lead.preferred_date.strftime("%A, %B %d, %Y")}
        Preferred Appointment Time Of Day: #{@lead.preferred_time_range}
      DESCRIPTION

      Tacokit.create_card(
        ENV.fetch('TRELLO_LEADS_LIST_ID'),
        "#{@lead.person_name} - Website",
        {
          due: 3.days.from_now.iso8601,
          desc: description,
          pos: 'top'
        }
      )
    end

    def update
      @lead ||= Lead.find_by!(owning_organization: current_organization, uuid: params[:uuid])
      @lead.assign_attributes(permitted_parameters)
      @lead.save!
    end

    def confirm
      @lead ||= Lead.find_by!(owning_organization: current_organization, uuid: params[:uuid])
      @lead.status = :SUBMITTED
      @lead.save!
    end

    def send_confirmation_emails
      @lead ||= Lead.find_by!(owning_organization: current_organization, uuid: params[:uuid])
      Website::LeadsMailer.confirm_external_email(current_organization: current_organization, lead: @lead).deliver_now
      Website::LeadsMailer.confirm_internal_email(current_organization: current_organization, lead: @lead).deliver_now
    end

    def load_items
      @items = Item.where(owning_organization: current_organization, status: :ACTIVE, form: :ABSTRACT, primary_kind: :SERVICE)
    end

    def permitted_parameters
      params.require(:lead).permit(
        :email_address,
        :person_name,
        :phone_country_code,
        :phone_number,
        :preferred_conversation_channel,
        :preferred_date,
        :preferred_time_range,
        :message,
        item_ids: []
      )
    end
  end
end

app/controllers/website/organizations_controller.rb
module Website
  class OrganizationsController < WebsiteController
    def index
    end

    def show
    end
  end
end

app/controllers/website/pages_controller.rb
module Website
  class PagesController < WebsiteController
    before_action :load_phones
    before_action :load_treatments

    def home
      @social_proofs = SocialProof.where(
        owning_organization: @current_organization
      )
      @external_testimonials = Testimonial.where(
        owning_organization: @current_organization,
        status: :ACCEPTED,
        source: :EXTERNAL
      ).order(
        date: :desc
      ).limit(10)
      @internal_testimonials = Testimonial.where(
        owning_organization: @current_organization,
        status: :ACCEPTED,
        source: :INTERNAL
      ).order(
        date: :desc
      ).limit(9)
    end

    def about_us
      @external_testimonials = Testimonial.where(
        owning_organization: @current_organization,
        status: :ACCEPTED,
        source: :EXTERNAL
      ).order(
        date: :desc
      ).limit(10)
    end

    def contact_us
    end

    def price_list
      @categories = Category.includes(:items).all
    end

    def the_team
      @primary_producers = Person.where(
        owning_organization: @current_organization,
        status: :ACTIVE,
        primary_kind: :PRODUCER,
      )
      .where(
        name: [
          'Irving Cota',
          'Marcia Bustamante',
          'Aldo Sanchez'
        ]
      )
      @secondary_producers = Person.where(
        owning_organization: @current_organization,
        status: :ACTIVE,
        primary_kind: :PRODUCER
      ).where.not(
        name: [
          'Irving Cota',
          'Marcia Bustamante',
          'Aldo Sanchez'
        ]
      )
      @external_testimonials = Testimonial.where(
        owning_organization: @current_organization,
        status: :ACCEPTED,
        source: :EXTERNAL
      ).order(
        date: :desc
      ).limit(10)
    end

    def virtual_tour
      @social_proofs = SocialProof.where(
        owning_organization: @current_organization
      )
      @external_testimonials = Testimonial.where(
        owning_organization: @current_organization,
        status: :ACCEPTED,
        source: :EXTERNAL
      ).order(
        date: :desc
      ).limit(10)
      @internal_testimonials = Testimonial.where(
        owning_organization: @current_organization,
        status: :ACCEPTED,
        source: :INTERNAL
      ).order(
        date: :desc
      ).limit(9)
    end
  end
end

app/controllers/website/posts_controller.rb
module Website
  class PostsController < WebsiteController
    before_action :load_phones
    before_action :load_treatments
    before_action :generate_archive


    def index
      # params[:year] ||= DateTime.now.year
      # params[:month] ||= DateTime.now.month

      @posts = Post.where(
        owning_organization: current_organization,
        status: :PUBLISHED
      ).order(published_at: :desc)
    end

    def show
      @post = Post.find_by(
        owning_organization: current_organization,
        status: :PUBLISHED,
        id: params[:id]
      )
    end

    private

    def generate_archive
      @archive = {}

      year_groups = Post.where(
        owning_organization: current_organization,
        status: :PUBLISHED
      ).group_by { |p| p.created_at.beginning_of_year }

      year_groups.each do |year_datetime, posts|
        month_groups = Post.where(
          id: posts.map(&:id)
        ).group_by { |p| p.created_at.beginning_of_month }

        @archive[year_datetime.year] = {
          count: posts.count,
          objects: posts,
          months: month_groups.map do |month_datetime, posts|
            [
              month_datetime.month,
              {
                count: posts.count,
                objects: posts
              }
            ]
          end.to_h
        }
      end
    end
  end
end

app/controllers/website/states_controller.rb
module Website
  class StatesController < WebsiteController
    def index
    end

    def show
    end
  end
end

app/controllers/website/treatments_controller.rb
module Website
  class TreatmentsController < WebsiteController
    before_action :load_phones
    before_action :load_treatments

    def index
    end

    def show
      @treatment = Item.find_by!(
        owning_organization: @current_organization,
        key: params[:id].gsub('-', '_')
      )
      @item_testimonial_mappings = ItemTestimonialMapping.where(
        owning_organization: @current_organization,
        item: @treatment
      )
      @testimonials = Testimonial.where(
        owning_organization: @current_organization,
        id: @item_testimonial_mappings.pluck(:id),
        status: :ACCEPTED
      )
      @external_testimonials = @testimonials.where(
        source: :EXTERNAL
      ).order(
        date: :desc
      ).limit(10)
      @internal_testimonials = @testimonials.where(
        source: :INTERNAL
      ).order(
        date: :desc
      ).limit(9)
    end
  end
end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController
  protect_from_forgery with: :exception
  layout 'website/layouts/application'

  protected

  def load_phones
    @phones = Phone.where(
      owning_organization: current_organization,
      phoneable: @current_organization
    )
  end

  def load_treatments
    @treatments = Item.where(
      owning_organization: current_organization,
      status: :ACTIVE,
      form: :ABSTRACT,
      primary_kind: :SERVICE
    )
  end
end

app/views/website/leads/_form.html.erb
<%= form_with(model: [:website, lead], local: true, url: url) do |form| %>
  <% if lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lead.errors.count, "error") %> prohibited this lead from being saved:</h2>
      <ul>
      <% lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='form-group'>
    <%= form.label 'Name' %>
    <%= form.text_field :person_name, { placeholder: 'Your Name', required: true, class: 'form-control' } %>
  </div>
  <div class='form-group'>
    <%= form.label 'Email address' %>
    <%= form.email_field :email_address, { placeholder: 'Your Email', required: true, class: 'form-control' } %>
  </div>
  <%= form.hidden_field :phone_country_code, value: 'US' %>
  <div class='form-group'>
    <%= form.label 'Phone number' %>
    <%= form.telephone_field :phone_number, { placeholder: 'Your Phone Number', required: true, class: 'form-control' } %>
  </div>
  <div class='form-group'>
    <%= form.label 'Preferred arrival date' %>
    <%= form.date_field :preferred_date, { min: 1.day.ago.strftime('%Y-%m-%d'), required: true, class: 'form-control date-picker-override' } %>
  </div>
  <div class='form-group'>
    <%= form.label 'Preferred arrival time' %>
    <%= form.select :preferred_time_range, Lead.preferred_time_ranges.keys.to_a.map{|k| [k.humanize, k]}, { include_blank: 'Please select one' }, { required: true, class: 'form-control' } %>
  </div>
  <div class='form-group'>
    <%= form.label 'Preferred conversation channel' %>
    <%= form.select :preferred_conversation_channel, Lead.preferred_conversation_channels.keys.to_a.map{|k| [k.humanize, k]}, { include_blank: 'Please select one' }, { required: true, class: 'form-control' } %>
  </div>
  <div class='form-group'>
    <%= form.label 'Interested In' %>
    <%= form.select :item_ids, @items.map{|i| [i.name, i.id] }, {}, { required: true, multiple: true, size: @items.count, class: 'form-control' } %>
  </div>
  <div class='form-group'>
    <%= form.label 'Optional Message' %>
    <%= form.text_area :message, { required: false, rows: 5, class: 'form-control' } %>
  </div>
  <hr class="mb-4">
  <div class="actions">
    <%= form.submit 'Submit', class: 'form-control btn btn-primary' %>
  </div>
  <p class='disclaimer text-center'>
    By submitting this form, you are confirming you have read and agree to our Terms and Privacy Statement.
  </p>
<% end %>

app/views/website/leads/edit.html.erb
<%= render 'website/partials/secondary_header', current_organization: @current_organization %>
<div class="container">
  <div class="row">
    <div class="col-12">
      <h2>Schedule Appointment</h2>
    </div>
    <div class="col-md-8 col-sm-12">
      <%= render 'form', lead: @lead, url: update_and_confirm_and_send_confirmation_emails_website_lead_path(@lead) %>
    </div>
    <div class="col-md-4 col-sm-12 d-none d-md-block">
      <%= render 'website/partials/working_hours', phones: @phones, current_organization: @current_organization %>
    </div>
  </div>
</div>
<%= render 'website/partials/secondary_footer', current_organization: @current_organization %>

app/views/website/leads/new.html.erb
<%= render 'website/partials/secondary_header', current_organization: @current_organization %>
<div class="container">
  <div class="row">
    <div class="col-12">
      <h3>Schedule Appointment</h3>
    </div>
    <div class="col-md-8 col-sm-12">
      <%= render 'form', lead: @lead, url: create_and_confirm_and_send_confirmation_emails_website_leads_path %>
    </div>
    <div class="col-md-4 col-sm-12 d-none d-md-block">
      <%= render 'website/partials/working_hours', phones: @phones, current_organization: @current_organization %>
    </div>
  </div>
</div>
<%= render 'website/partials/secondary_footer', current_organization: @current_organization %>

app/views/website/leads/thanks.html.erb
<%= render 'website/partials/secondary_header', current_organization: @current_organization %>
<%= render 'website/partials/we_are_waiting_for_you', primary_text: "Thanks #{@lead.person_name.titleize} for your appointment on #{@lead.preferred_date.strftime("%A, %B %d, %Y")}.", secondary_text: 'One of our patient coordinators will contact you to help you in every step of the process' %>
<div class='container'>
  <div class='row'>
    <div class='col-12'>
      <p class='text-center disclaimer'>You will be contacted by Baja Smile Dentistry within the next 24 hours to confirm the exact time of your appointment. If you require booking flights or need to finalize your travel arrangements, please confirm your travel dates back to us as soon as possible so we may confirm your appointment.</p>
    </div>
  </div>
</div>
<%= render 'website/partials/secondary_footer', current_organization: @current_organization %>

<% if Rails.env == 'production' %>
  <script>
  </script>
<% end %>